In [2]:
from google.colab import files
uploaded= files.upload()

Saving sample_-_superstore.xls to sample_-_superstore.xls

In [6]:
import pandas as pd

In [8]:
df= pd.read_excel("sample_-_superstore.xls")

In [9]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,US-2023-103800,2023-01-03,2023-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,2,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
2,3,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
3,4,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748
4,5,US-2023-141817,2023-01-05,2023-01-12,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840

In [11]:
df.shape

(10194, 21)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  object
 2   Order Date      10194 non-null  datetime64[ns]
 3   Ship Date       10194 non-null  datetime64[ns]
 4   Ship Mode       10194 non-null  object
 5   Customer ID     10194 non-null  object
 6   Customer Name   10194 non-null  object
 7   Segment         10194 non-null  object
 8   Country/Region  10194 non-null  object
 9   City            10194 non-null  object
 10  State/Province  10194 non-null  object
 11  Postal Code     10194 non-null  object
 12  Region          10194 non-null  object
 13  Product ID      10194 non-null  object
 14  Category        10194 non-null  object
 15  Sub-Category    10194 non-null  object
 16  Product Name    10194 non-null  object
 17  Sales           10194 non-null  float64
 18  Quantity        10194 non-null  int64
 19  Discount        10194 non-null  float64
 20  Profit          10194 non-null  float64
dtypes: datetime64[ns](2), float64(3), int64(2), object(14)
memory usage: 1.6+ MB

In [13]:
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country/Region    0
City              0
State/Province    0
Postal Code       0
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
Quantity          0
Discount          0
Profit            0
dtype: int64

In [15]:
df.describe()

,Row ID,Order Date,Ship Date,Sales,Quantity,Discount,Profit
count,10194.000000,10194,10194,10194.000000,10194.000000,10194.000000,10194.000000
mean,5097.500000,2025-04-29 11:48:25.002942720,2025-05-03 10:52:45.626839296,228.225854,3.791838,0.155385,28.673417
min,1.000000,2023-01-03 00:00:00,2023-01-07 00:00:00,0.444000,1.000000,0.000000,-6599.978000
25%,2549.250000,2024-05-14 00:00:00,2024-05-19 00:00:00,17.220000,2.000000,0.000000,1.760800
50%,5097.500000,2025-06-25 00:00:00,2025-06-28 00:00:00,53.910000,3.000000,0.200000,8.690000
75%,7645.750000,2026-05-14 00:00:00,2026-05-18 00:00:00,209.500000,5.000000,0.200000,29.297925
max,10194.000000,2026-12-30 00:00:00,2027-01-05 00:00:00,22638.480000,14.000000,0.800000,8399.976000
std,2942.898656,NaN,NaN,619.906839,2.228317,0.206249,232.465115

In [16]:
df.columns.tolist()

['Row ID',
 'Order ID',
 'Order Date',
 'Ship Date',
 'Ship Mode',
 'Customer ID',
 'Customer Name',
 'Segment',
 'Country/Region',
 'City',
 'State/Province',
 'Postal Code',
 'Region',
 'Product ID',
 'Category',
 'Sub-Category',
 'Product Name',
 'Sales',
 'Quantity',
 'Discount',
 'Profit']

In [18]:
df.duplicated().sum()

np.int64(0)

In [19]:
df['Segment'].unique()

array(['Consumer', 'Home Office', 'Corporate'], dtype=object)

In [20]:
df['Region'].unique()

array(['Central', 'East', 'South', 'West'], dtype=object)

In [21]:
df['Category'].unique()

array(['Office Supplies', 'Furniture', 'Technology'], dtype=object)

In [22]:
df['Ship Mode'].unique()

array(['Standard Class', 'First Class', 'Second Class', 'Same Day'],
      dtype=object)

In [23]:
df[['Sales','Quantity','Discount','Profit']].describe()

              Sales      Quantity      Discount        Profit
count  10194.000000  10194.000000  10194.000000  10194.000000
mean     228.225854      3.791838      0.155385     28.673417
std      619.906839      2.228317      0.206249    232.465115
min        0.444000      1.000000      0.000000  -6599.978000
25%       17.220000      2.000000      0.000000      1.760800
50%       53.910000      3.000000      0.200000      8.690000
75%      209.500000      5.000000      0.200000     29.297925
max    22638.480000     14.000000      0.800000   8399.976000

In [29]:
df['Year']= df['Order Date'].dt.year
df['Month']= df['Order Date'].dt.month
df['Month_Name']= df['Order Date'].dt.month_name()

In [30]:
df[['Order Date','Year','Month','Month_Name']].head()

  Order Date  Year  Month Month_Name
0 2023-01-03  2023      1    January
1 2023-01-04  2023      1    January
2 2023-01-04  2023      1    January
3 2023-01-04  2023      1    January
4 2023-01-05  2023      1    January

In [31]:
total_sales= df['Sales'].sum()
total_profit= df['Profit'].sum()
total_Quantity= df['Quantity'].sum()
total_orders= df['Order ID'].nunique()
total_customers= df['Customer ID'].nunique()
totalCustomers_name= df['Customer Name'].nunique()

In [33]:
print("Total sales:", total_sales)
print("Total Profit:", total_profit)
print("Total Quantity:", total_Quantity)
print("Total Orders:", total_orders)
print("Total Customers:", total_customers)
print("Total Customers by name:", totalCustomers_name)

Total sales: 2326534.3543
Total Profit: 292296.8145999999
Total Quantity: 38654
Total Orders: 5111
Total Customers: 804
Total Customers by name: 800

In [34]:
df.groupby("Customer ID")['Customer Name'].nunique().sort_values(ascending=False).head(10)

Customer ID
ZD-21925    1
AA-10315    1
AA-10375    1
AA-10480    1
VD-21670    1
VB-21745    1
TZ-21580    1
TW-21025    1
TT-21460    1
TT-21265    1
Name: Customer Name, dtype: int64

In [35]:
df.groupby("Customer Name")['Customer ID'].nunique().sort_values(ascending=False).head(10)

Customer Name
Harry Olson          5
Melanie Seite        1
Michael Chen         1
Michael Dominguez    1
Michael Grace        1
Michael Granlund     1
Michael Kennedy      1
Michael Knudson      1
Michael Moore        1
Michael Nguyen       1
Name: Customer ID, dtype: int64

In [36]:
nameIdCheck= (df.groupby("Customer Name")['Customer ID'].nunique().sort_values(ascending=False))
nameIdCheck[nameIdCheck>1]
#

Customer Name
Harry Olson    5
Name: Customer ID, dtype: int64

In [37]:
nameIdCheck[nameIdCheck>1].count()

np.int64(1)

In [39]:
df[df['Customer Name']=='Harry Olson'][['Customer ID','Customer Name']].drop_duplicates()

     Customer ID Customer Name
2036    HO-15230   Harry Olson
5009    HO-15234   Harry Olson
5010    HO-15233   Harry Olson
5011    HO-15232   Harry Olson
5012    HO-15231   Harry Olson

In [40]:
df[df['Customer Name']=='Harry Olson'][['Customer ID','Customer Name','City','State/Province','Postal Code', 'Region']].drop_duplicates()

,Customer ID,Customer Name,City,State/Province,Postal Code,Region
2036,HO-15230,Harry Olson,Charlottetown,Prince Edward Island,C0A,East
5009,HO-15234,Harry Olson,Charlottetown,Prince Edward Island,C0A,East
5010,HO-15233,Harry Olson,Charlottetown,Prince Edward Island,C0A,East
5011,HO-15232,Harry Olson,Charlottetown,Prince Edward Island,C0A,East
5012,HO-15231,Harry Olson,Charlottetown,Prince Edward Island,C0A,East

there is a customer identifer inconsistency in the source dataset but  the CUSTOMER ID will serve as my primary identifier because it uniquely identify customers accounts

In [41]:
# Overall profit margin
profit_margin= (total_profit/total_sales)*100
print("Overall profit margin:", round(profit_margin, 2), '%')

Overall profit margin: 12.56 %

In [52]:
# Sales/ Profit by year
df.groupby('Year')[['Sales','Profit']].sum()

            Sales      Profit
Year
2023  494040.2121  51684.2957
2024  472993.0310  62020.9695
2025  613933.5800  82665.2018
2026  745567.5312  95926.3476

In [56]:
# sales/ Profit by category
df.groupby('Category')[['Sales','Profit']].sum().sort_values(by='Sales', ascending=False)

                       Sales       Profit
Category
Technology       839893.2790  146543.3756
Furniture        754747.7613   19729.9956
Office Supplies  731893.3140  126023.4434

In [58]:
# sales/profit by region
df.groupby('Region')[['Sales','Profit']].sum().sort_values(by='Sales', ascending=False)

               Sales       Profit
Region
West     739813.6085  110798.8170
East     691828.1680   94883.2603
Central  503170.6728   39865.3070
South    391721.9050   46749.4303

In [62]:
df.groupby('Region')[['Discount','Profit']].mean().sort_values(by='Profit', ascending=False)

         Discount     Profit
Region
West     0.108946  34.060503
East     0.143436  31.776042
South    0.147253  28.857673
Central  0.241002  17.072937

In [63]:
df.groupby('Category')[['Discount','Profit']].mean().sort_values(by='Discount', ascending=False)

                 Discount     Profit
Category
Furniture        0.172962   8.964105
Office Supplies  0.156348  20.565183
Technology       0.131475  78.575537

In [64]:
df[df['Region']=='Central'].groupby('Category')[['Discount','Profit','Sales']].mean().sort_values(by='Discount', ascending=False)

                 Discount     Profit       Sales
Category
Furniture        0.297402  -5.777746  339.252890
Office Supplies  0.253566   6.272784  117.634062
Technology       0.133095  80.231981  405.753124

In [67]:
df[df['Region']=='Central'].groupby('Sub-Category')[['Discount','Profit','Sales']].sum().sort_values(by='Profit', ascending=False)

              Discount      Profit       Sales
Sub-Category
Copiers           1.80  15608.8413  37259.5700
Phones           24.40  12323.0267  72403.2820
Accessories      22.80   7251.6306  33956.0760
Paper            41.40   6971.9005  17491.9020
Chairs           30.10   6670.8633  85941.1420
Storage          26.40   1974.6065  45982.8980
Envelopes         7.60   1777.5283   4636.8720
Art              21.60   1195.1591   5765.3400
Labels            8.60   1073.0794   2451.4720
Fasteners         7.40    236.6186    778.0300
Supplies          5.20   -661.8881   9467.3720
Binders         189.20   -958.3051  58060.7900
Machines          6.90  -1486.0666  26797.3840
Bookcases        11.64  -1997.9043  24157.1768
Appliances       55.20  -2638.6175  23582.0330
Tables           18.90  -3559.6504  39154.9710
Furnishings      83.60  -3915.5153  15284.3620

In [72]:
df[(df['Region']=='Central') & (df['Category']=='Furniture')].groupby('Product Name')[['Discount','Profit','Sales']].mean().sort_values(by='Profit', ascending=False)

,Discount,Profit,Sales
Product Name,,,
Hon Pagoda Stacking Chairs,0.0,770.3520,2567.840
Office Star - Professional Matrix Back Chair with 2-to-1 Synchro Tilt and Mesh Fabric Seat,0.0,673.8816,2807.840
Hon Olson Stacker Stools,0.0,394.2680,1408.100
Hon Olson Stacker Chairs,0.0,383.9310,1323.900
"Hon Deluxe Fabric Upholstered Stacking Chairs, Rounded Back",0.0,365.9700,1219.900
...,...,...,...
Luxo Professional Fluorescent Magnifier Lamp with Clamp-Mount Base,0.6,-356.7280,419.680
Tenex Antistatic Computer Chair Mats,0.6,-427.4500,341.960
Hon Rectangular Conference Tables,0.5,-525.6405,796.425
Bretford “Just In Time” Height-Adjustable Multi-Task Work Tables,0.5,-538.4460,626.100
BoxOffice By Design Rectangular and Half-Moon Meeting Room Tables,0.5,-566.5625,765.625

In [74]:
# Investigating negative-profit products
df[df['Profit']<0][['Product Name','Sales','Discount','Profit']].sort_values(by='Profit').head(20)

,Product Name,Sales,Discount,Profit
6398,Cubify CubeX 3D Printer Double Head Print,4499.985,0.7,-6599.9780
9318,Cubify CubeX 3D Printer Triple Head Print,7999.980,0.5,-3839.9904
821,GBC DocuBind P400 Electric Binding System,2177.584,0.8,-3701.8928
7441,Lexmark MX611dhe Monochrome Laser Printer,2549.985,0.7,-3399.9800
9845,Ibico EPK-21 Electric Binding System,1889.990,0.8,-2929.4845
4037,Cubify CubeX 3D Printer Double Head Print,1799.994,0.7,-2639.9912
9557,Fellowes PB500 Electric Punch Plastic Comb Bin...,1525.188,0.8,-2287.7820
2108,Chromcraft Bull-Nose Wood Oval Conference Tabl...,4297.644,0.4,-1862.3124
4570,GBC DocuBind P400 Electric Binding System,1088.792,0.8,-1850.9464
226,Cisco TelePresence System EX90 Videoconferenci...,22638.480,0.5,-1811.0784
3203,"Riverside Palais Royal Lawyers Bookcase, Royal...",3083.430,0.5,-1665.0522
1549,GBC DocuBind TL300 Electric Binding System,896.990,0.8,-1480.0335
1063,Lexmark MX611dhe Monochrome Laser Printer,8159.952,0.4,-1359.9920
9119,GBC DocuBind P400 Electric Binding System,1633.188,0.7,-1306.5504
8331,GBC DocuBind TL300 Electric Binding System,1614.582,0.7,-1237.8462
2354,Hoover Upright Vacuum With Dirt Cup,463.248,0.8,-1181.2824
8638,Fellowes PB500 Electric Punch Plastic Comb Bin...,762.594,0.8,-1143.8910
6846,GBC Ibimaster 500 Manual ProClick Binding System,760.980,0.8,-1141.4700
3893,GBC Ibimaster 500 Manual ProClick Binding System,1598.058,0.7,-1065.3720
8829,Martin Yale Chadless Opener Electric Letter Op...,4663.736,0.2,-1049.3406

In [75]:
df[df['Profit']<0].groupby('Category')[['Sales','Discount','Profit']].mean()

                      Sales  Discount      Profit
Category
Furniture        356.107045  0.369590  -84.255715
Office Supplies  102.856921  0.616147  -63.233662
Technology       439.899974  0.333579 -142.361322

In [76]:
df[df['Profit']<0].groupby('Sub-Category')[['Sales','Discount','Profit']].sum().sort_values(by='Profit')

                    Sales  Discount      Profit
Sub-Category
Binders        36200.5010    455.70 -38563.4860
Tables        105699.3760     74.75 -32503.6583
Machines       72456.2530     25.60 -30118.6682
Bookcases      48217.3288     39.39 -12349.8096
Chairs         93460.1680     62.00 -10135.0373
Appliances      3382.5340     53.60  -8629.6412
Phones         35797.8400     46.60  -7530.6235
Furnishings    13293.4840     94.40  -6686.6785
Storage        38429.1440     32.70  -6480.2220
Supplies       14067.1760      6.60  -3015.6219
Accessories    10958.8000     18.20   -930.6265
Fasteners        149.2800      2.40    -33.1952
Labels            82.9200      1.10    -31.3860
Art               39.9600      0.60    -23.9760
Paper             14.0000      0.60     -6.3000

In [77]:
df.groupby('Sub-Category')[['Sales','Discount','Profit']].mean().sort_values(by='Discount', ascending=False)

                    Sales  Discount      Profit
Sub-Category
Binders        133.950182  0.369057   20.301098
Machines      1623.290863  0.304274   29.589546
Tables         638.098718  0.258129  -54.457687
Bookcases      497.246570  0.215259  -15.655490
Chairs         529.602916  0.169243   42.939325
Appliances     228.297859  0.164557   38.669798
Copiers       2153.504143  0.157143  801.341950
Phones         367.489081  0.152602   49.890173
Furnishings     94.745417  0.138057   13.767833
Envelopes       64.563914  0.079688   27.296971
Fasteners       37.258690  0.078603   10.605397
Accessories    215.974604  0.078452   54.111788
Supplies       243.361969  0.076042   -6.101013
Storage        262.435227  0.075117   24.865784
Art             33.689420  0.075030    8.103771
Paper           57.471487  0.075000   24.936060
Labels          34.497397  0.070924   15.143418

In [79]:
df[df['Sub-Category']=='Binders'][['Sales','Discount','Profit']].describe()

             Sales     Discount       Profit
count  1548.000000  1548.000000  1548.000000
mean    133.950182     0.369057    20.301098
std     559.368482     0.311167   303.893602
min       0.556000     0.000000 -3701.892800
25%       8.251500     0.200000    -6.008400
50%      18.706500     0.200000     4.123800
75%      52.218000     0.700000    16.001300
max    9892.740000     0.800000  4946.370000

In [81]:
df[df['Sub-Category']=='Bookcases'].groupby('Discount')['Profit'].mean().sort_index()

Discount
0.00    101.261862
0.15     27.288298
0.20      3.512254
0.30    -55.587260
0.32    -88.560656
0.50   -236.433983
0.70   -240.737824
Name: Profit, dtype: float64

In [82]:
df[df['Sub-Category']=='Tables'].groupby('Discount')['Profit'].mean().sort_index()

Discount
0.00    175.459536
0.20     -4.144417
0.30    -62.389957
0.40   -215.831957
0.45   -226.646464
0.50   -239.316314
Name: Profit, dtype: float64

In [83]:
df[['Discount','Profit']].corr()

          Discount    Profit
Discount  1.000000 -0.218882
Profit   -0.218882  1.000000

## 5. Profitability Analysis

In [86]:
# Category profitability
category_analysis=(df.groupby('Category')
.agg(
    Sales=('Sales','sum'),
    Profit=('Profit','sum'),
    Quantity=('Quantity','sum')
    )
)
category_analysis['Profit Margin']= (category_analysis['Profit']/category_analysis['Sales']*100)
category_analysis.sort_values(by='Sales', ascending=False).round(2)

                     Sales     Profit  Quantity  Profit Margin
Category
Technology       839893.28  146543.38      7017          17.45
Furniture        754747.76   19730.00      8369           2.61
Office Supplies  731893.31  126023.44     23268          17.22

In [90]:
# sub-category analysis
sub_category_analysis=(df.groupby('Sub-Category')
.agg(
    Sales=('Sales','sum'),
    Profit=('Profit','sum'),
    Quantity=('Quantity','sum')
    )
)
sub_category_analysis['profit Margin']= (sub_category_analysis['Profit']/sub_category_analysis['Sales']*100)
sub_category_analysis.sort_values(by='Profit')

                    Sales      Profit  Quantity  profit Margin
Sub-Category
Tables        208020.1820 -17753.2061      1261      -8.534367
Bookcases     115361.2043  -3632.0736       878      -3.148436
Supplies       46725.4980  -1171.3945       653      -2.506971
Fasteners       8532.2400   2428.6358       980      28.464223
Machines      189925.0310   3461.9769       442       1.822812
Labels         12695.0420   5572.7780      1410      43.897279
Art            27659.0140   6653.1962      3092      24.054351
Envelopes      16528.3620   6988.0247       914      42.278991
Furnishings    95598.1260  13891.7430      3799      14.531397
Appliances    108213.1850  18329.4844      1750      16.938310
Storage       224644.5540  21285.1115      3191       9.475018
Chairs        335768.2490  27223.5323      2431       8.107834
Binders       207354.8810  31426.1003      6071      15.155708
Paper          79540.5380  34511.5070      5207      43.388576
Accessories   167380.3180  41936.6357      2976      25.054700
Phones        331842.6400  45050.8265      3357      13.575961
Copiers       150745.2900  56093.9365       242      37.211071

In [91]:
# regional profitability
region_analysis=(df.groupby('Region')
.agg(
    Sales=('Sales','sum'),
    Profit=('Profit','sum'),
    Quantity=('Quantity','sum')
    )
)
region_analysis['profit Margin']= (region_analysis['Profit']/region_analysis['Sales']*100)
region_analysis.sort_values(by='Sales', ascending=False).round(2)

             Sales     Profit  Quantity  profit Margin
Region
West     739813.61  110798.82     12466          14.98
East     691828.17   94883.26     11159          13.71
Central  503170.67   39865.31      8820           7.92
South    391721.90   46749.43      6209          11.93

In [102]:
# Create a copy for Tableau
tableau_df= df.copy()

In [93]:
tableau_df.shape

(10194, 24)

In [95]:
tableau_df.columns.to_list()

['Row ID',
 'Order ID',
 'Order Date',
 'Ship Date',
 'Ship Mode',
 'Customer ID',
 'Customer Name',
 'Segment',
 'Country/Region',
 'City',
 'State/Province',
 'Postal Code',
 'Region',
 'Product ID',
 'Category',
 'Sub-Category',
 'Product Name',
 'Sales',
 'Quantity',
 'Discount',
 'Profit',
 'Year',
 'Month',
 'Month_Name']

In [97]:
tableau_df.isnull().sum().sum()

np.int64(0)

In [100]:
#tableau_df['Year_Month']= tableau_df['Order Date'].dt.strftime('%Y-%m') or
tableau_df['Year_Month']= tableau_df['Order Date'].dt.to_period('M').astype(str)

In [101]:
tableau_df[['Order Date','Year','Month_Name','Year_Month']].head()

  Order Date  Year Month_Name Year_Month
0 2023-01-03  2023    January    2023-01
1 2023-01-04  2023    January    2023-01
2 2023-01-04  2023    January    2023-01
3 2023-01-04  2023    January    2023-01
4 2023-01-05  2023    January    2023-01

In [103]:
tableau_df.to_csv('Superstore_Tableau_ready.csv', index=False)

In [105]:
import os
os.path.getsize('Superstore_Tableau_ready.csv')

2624554

In [106]:
from google.colab import files
files.download('Superstore_Tableau_ready.csv')

In [107]:
# profit contribution by category
category_analysis['profit_contribution']= (category_analysis['Profit']/category_analysis['Profit'].sum()*100)
category_analysis.sort_values(by='profit_contribution', ascending=False).round(2)

,Sales,Profit,Quantity,Profit Margin,profit_contribution
Category,,,,,
Technology,839893.28,146543.38,7017,17.45,50.14
Office Supplies,731893.31,126023.44,23268,17.22,43.11
Furniture,754747.76,19730.00,8369,2.61,6.75

In [108]:
# profit contribution by region
region_analysis['profit_contribution']= (region_analysis['Profit']/region_analysis['Profit'].sum()*100)
region_analysis.sort_values(by='profit_contribution', ascending=False).round(2)

             Sales     Profit  Quantity  profit Margin  profit_contribution
Region
West     739813.61  110798.82     12466          14.98                37.91
East     691828.17   94883.26     11159          13.71                32.46
South    391721.90   46749.43      6209          11.93                15.99
Central  503170.67   39865.31      8820           7.92                13.64